version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    # networks:
    #   app_net:
    #     ipv4_address: 192.168.20.20

  pgadmin:
    container_name: pgadmin_gui
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 5050:80
    # networks:
    #   app_net:
    #     ipv4_address: 192.168.20.30
    depends_on:
      - db

volumes:
  pgadmin_data:
# networks:
#   app_net:
#     ipam:
#       driver: default
#       config:
#         - subnet: "19.168.20.0/24"
